apiVersion: v1
kind: Service
metadata:
  name: iris-inference-service
spec:
  type: NodePort
  selector:
    app: iris-inference-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
